# Generated by Django 4.1 on 2022-09-28 21:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensajes', '0002_alter_mensaje_options_remove_mensaje_creado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelbase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tiempo', models.DateTimeField(auto_now_add=True)),
                ('actualizar', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
