# Generated by Django 4.1 on 2022-09-11 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodeporte', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('fecha', models.DateField(blank=True, default=datetime.date(2022, 9, 11), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiponoticia', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('fecha', models.DateField(blank=True, default=datetime.date(2022, 9, 11), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
