# Generated by Django 4.1 on 2022-09-19 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppsProyecto', '0002_tag_alter_deportes_fecha_alter_noticias_fecha_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportes',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2022, 9, 19), null=True),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2022, 9, 19), null=True),
        ),
    ]
