# Generated by Django 4.1 on 2022-09-20 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppsProyecto', '0003_alter_deportes_fecha_alter_noticias_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportes',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2022, 9, 20), null=True),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2022, 9, 20), null=True),
        ),
    ]
