# Generated by Django 4.1 on 2022-09-26 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppsProyecto', '0006_alter_avatar_user_delete_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticias',
        ),
    ]
