# Generated by Django 4.1 on 2022-09-28 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppsProyecto', '0008_post_fecha_alter_deportes_fecha_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
