# Generated by Django 4.1 on 2022-09-28 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppsProyecto', '0009_delete_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deportes',
        ),
    ]
