# Generated by Django 4.1 on 2022-09-29 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppsProyecto', '0011_alter_post_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2022, 9, 29), null=True),
        ),
    ]
